### ISSUE TITLE
binding outgoing connection on same ip on which the connection is accepted

### ISSUE THREAD

**Issue by deepika-maj** [clue/reactphp-socks#89]
I have multiple IPs on my server and have started the socks server to listen on all of it using:
```php
$loop = Factory::create();
$server = new Server($loop, null, ['user' => 'pass']);
$socket = new Socket('0.0.0.0:1080', $loop);
$server->listen($socket);
$loop->run();
```

now, it would be great to have an option or a way to connect to remote host using same ip on which the socks connection is accepted.

currently the only way to achieve this is by creating individual Socket, individual Server and passing individual Connector having `bindto` option.

**Comment by clue** [comment]
@deepika-maj Thank you for reporting, this would indeed be an interesting feature addition :+1: 

For now, you should be able to run multiple server instances with a dedicated connector as suggested in your question.

In the future, we may add option to always bind the outgoing connection to the same address/interface from the incoming connection. Dynamically passing these parameters is not currently supported by the underlying https://github.com/reactphp/socket component and as such also not exposed by this library. Once this in merged upstream, we may have to perform some minor changes to expose the incoming address to the connector.

It's my understanding that making this the default behavior is probably not feasible, because it might break existing implementations and this doesn't seem to be the behavior every installation wants. In particular, if I'm using this proxy on a local address, I do not want to bind the outgoing connection to the local address. This means we will likely have to come up with some way to control this on the code level. Are you aware of any other libraries that provide such options?

There are currently no immediate plans to build this from my end (no demand at the moment and more important outstanding issues currently), but I would be really happy to accept PRs :+1: 

*(If you need this for a commercial project and if you want to help sponsor this feature, feel free to reach out and send me an email and I'm sure this is something we can work out)*

**Comment by clue** [comment]
I still think that this feature makes perfect sense :+1: However, there are currently no immediate plans to build this from my end (no demand at the moment and more important outstanding issues currently), but I would be really happy to accept PRs :+1: 

If you need this for a commercial project and you want to help sponsor this feature, feel free to reach out and I'm happy to take a look.
