### ISSUE TITLE
Invalid socks4 response

### ISSUE THREAD

**Issue by alexmorbo** [clue/reactphp-socks#90]
Hi!

I use library but got error: `Invalid SOCKS response`
Then I saw code and find:
```
            if ($data['null'] !== 0x00) {
                throw new Exception('Invalid SOCKS response');
            }
```

Ok, i check what in $data, got:
```
^ array:4 [
  "null" => 4
  "status" => 90
  "port" => 80
  "ip" => 2987617527
]
```

If I comment this check, proxy works fine.

**Comment by clue** [comment]
@alexmorbo This is an interesting one!

It appears the server you're talking to does not follow the SOCKS4 protocol definition:

> A reply packet is sent to the client when this connection is established,
or when the request is rejected or the operation fails. 
>
>		+----+----+----+----+----+----+----+----+
>		| VN | CD | DSTPORT |      DSTIP        |
>		+----+----+----+----+----+----+----+----+
> \# of bytes:	   1    1      2              4
>
> VN is the version of the reply code and should be 0.[…]
> – https://www.openssh.com/txt/socks4.protocol

Do you happen to know which server software you're communicating with and/or how widespread this problem is? I'm not sure I like the idea of skipping this null byte check without having a better understanding of what's going on here.

**Comment by alexmorbo** [comment]
@clue this is socks from best-proxies.ru

**Comment by clue** [comment]
Does this happen consistently or only sporadically? It looks like this is a paid proxy provider, so I suppose they offer some kind of support level. Can you ask them to check this link and see if their servers follow the SOCKS4 protocol definition?

**Comment by alexmorbo** [comment]
@clue I will try, thanks
